# SITE STUFF
title: High Plains Regional Council
description: Serving the High Plains Region.
url: "https://hprc-au.github.io/hprc/" 

# THEME 
remote_theme: pages-themes/cayman@v0.2.0

# BUILD SETTINGS
plugins:
  - jekyll-remote-theme
  
header_pages:
  - index.md
  - our-council.md
  - services.md
  - contact.md

  exclude:
    - 'index.html'
